rules:
  - id: go.lang.security.audit.crypto.tls.tls-with-insecure-cipher
    languages:
      - go
    message: |
      Detected an insecure CipherSuite via the 'tls' module. This suite is considered weak.
      Use the function 'tls.CipherSuites()' to get a list of good cipher suites.
      See https://golang.org/pkg/crypto/tls/#InsecureCipherSuites
      for why and what other cipher suites to use.
    metadata:
      cwe: "CWE-327: Use of a Broken or Risky Cryptographic Algorithm"
      dev.semgrep.actions:
        - block
      owasp: "A9: Using Components with Known Vulnerabilities"
      references:
        - "https://golang.org/pkg/crypto/tls/#InsecureCipherSuites"
      semgrep.policy:
        id: 5253
        name: cart
        slug: cart
      semgrep.url: "https://semgrep.dev/r/go.lang.security.audit.crypto.tls.tls-with-insecure-cipher"
      source-rule-url: "https://github.com/securego/gosec/blob/master/rules/tls.go"
    pattern-either:
      - pattern: "tls.Config{..., CipherSuites: []$TYPE{..., tls.TLS_RSA_WITH_RC4_128_SHA,...}}\n"
      - pattern: "tls.Config{..., CipherSuites: []$TYPE{..., tls.TLS_RSA_WITH_AES_128_CBC_SHA256,...}}\n"
      - pattern: "tls.Config{..., CipherSuites: []$TYPE{..., tls.TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,...}}\n"
      - pattern: "tls.Config{..., CipherSuites: []$TYPE{..., tls.TLS_ECDHE_RSA_WITH_RC4_128_SHA,...}}\n"
      - pattern: "tls.Config{..., CipherSuites: []$TYPE{..., tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,...}}\n"
      - pattern: "tls.Config{..., CipherSuites: []$TYPE{..., tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,...}}\n"
      - pattern: "tls.CipherSuite{..., TLS_RSA_WITH_RC4_128_SHA ,...}\n"
      - pattern: "tls.CipherSuite{..., TLS_RSA_WITH_AES_128_CBC_SHA256 ,...}\n"
      - pattern: "tls.CipherSuite{..., TLS_ECDHE_ECDSA_WITH_RC4_128_SHA ,...}\n"
      - pattern: "tls.CipherSuite{..., TLS_ECDHE_RSA_WITH_RC4_128_SHA ,...}\n"
      - pattern: "tls.CipherSuite{..., TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 ,...}\n"
      - pattern: "tls.CipherSuite{..., TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 ,...}"
    severity: WARNING