version: '3.3'

services:
  prom:
    image: prom/prometheus:v2.26.0-rc.0
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - promnet

  jaeger:
    image: jaegertracing/all-in-one:1.22.0
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14267"
      - "14268:14268"
      - "14269"
      - "16686:16686"
      - "16687"
      - "9411:9411"
    restart: on-failure
    networks:
      - promnet

  kafka:
    container_name: kafka-telemetry
    image: krisgeus/docker-kafka
    environment:
      - AUTO_CREATE_TOPICS=true
      - ADV_HOST=localhost
      - ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://localhost:9093
      - LISTENERS=PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093
      - SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - INTER_BROKER=INTERNAL
    ports:
      - 3030:3030
      - 9092:9092
      - 2181:2181
    networks:
      - promnet

  cart:
    container_name: cart
    build: .
    environment:
      - CGO_ENABLED=0
      - GOPROXY=https://proxy.golang.org,direct
    ports:
      - 8888:8888
    networks:
      - promnet

networks:
  promnet:
    driver: bridge